// Report-Only: violations are logged to the browser console but nothing is
// blocked, so this can't break the pixels or product images. It lists every
// origin the site is known to load from; tighten it and switch the header to
// Content-Security-Policy once the console stays clean in production.
const cspReportOnly = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://connect.facebook.net https://www.redditstatic.com",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "img-src 'self' data: blob: https:",
  "connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://www.googletagmanager.com https://www.facebook.com https://connect.facebook.net https://*.reddit.com https://*.redditstatic.com",
  "frame-src 'self' https://www.facebook.com https://www.youtube.com https://www.youtube-nocookie.com",
  "frame-ancestors 'self'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
].join('; ');

const securityHeaders = [
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  // The browser default, stated explicitly so it can't regress — outbound
  // clicks to Sugargoo keep sending the origin as referrer.
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
  { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(), payment=()' },
  { key: 'Content-Security-Policy-Report-Only', value: cspReportOnly },
];

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    // No `domains`/`remotePatterns` on purpose. next/image is used only with
    // local files under public/assets; remote product photographs are resized
    // by the seller's own CDN (see lib/cdnImage.ts) rather than by Vercel's
    // optimizer, which is metered per unique source image and would be
    // expensive across a ~1000-product catalogue.
    formats: ['image/avif', 'image/webp'],
    // Capped at 1920: the largest local source is hero-main at 1632px wide and
    // Next never upscales, so 2048/3840 candidates would resolve to identical
    // pixels — wasted srcSet entries and wasted optimizer cache entries.
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 31536000,
  },
  compress: true,
  poweredByHeader: false,
  // The sitemap is generated by an API route, but /api/ is disallowed in
  // robots.txt and crawlers look for it at the root.
  rewrites: async () => [{ source: '/sitemap.xml', destination: '/api/sitemap.xml' }],
  redirects: async () => [
    // Jceaser was a misspelling of JCaesar and was merged into it.
    { source: '/brands/jceaser', destination: '/brands/jcaesar', permanent: true },
  ],
  headers: async () => [
    { source: '/:path*', headers: securityHeaders },
    {
      // Next serves public/ with `max-age=0` by default, so every repeat visit
      // pays a conditional request per asset. These filenames aren't
      // content-hashed, so this is deliberately not `immutable` — a re-encode
      // still reaches users within a week.
      source: '/assets/:path*',
      headers: [
        {
          key: 'Cache-Control',
          value: 'public, max-age=604800, stale-while-revalidate=2592000',
        },
      ],
    },
    // NOTE: /api/products sets its own Cache-Control in the handler
    // (pages/api/products.ts), varying by NODE_ENV. The duplicate rule that
    // used to live here disagreed with it on stale-while-revalidate.
  ],
};

module.exports = nextConfig;
