import type { NextApiRequest, NextApiResponse } from 'next';
import crypto from 'crypto';
import { logSignupEvent } from '../../../lib/db/analytics';

interface FacebookLead {
  email?: string;
  phone_number?: string;
  first_name?: string;
  last_name?: string;
  full_name?: string;
}

interface SugargooResponse {
  success?: boolean;
  code?: number;
  msg?: string;
  userId?: string;
  email?: string;
  password?: string;
  error?: string;
  data?: {
    userId?: string;
    email?: string;
    password?: string;
    status?: string;
    message?: string;
  };
}

interface LeadRegistrationLog {
  timestamp: string;
  source: 'facebook-lead-ads';
  email: string;
  name?: string;
  leadId?: string;
  sugargooResponse: {
    code: number;
    msg: string;
    userId?: string;
    status: 'success' | 'duplicate' | 'error';
  };
}

/**
 * Validates Facebook webhook signature
 * Facebook sends X-Hub-Signature-256 header with HMAC-SHA256
 */
function validateWebhookSignature(
  body: string,
  signature: string
): boolean {
  const appSecret = process.env.FACEBOOK_APP_SECRET;
  if (!appSecret) {
    console.error('FACEBOOK_APP_SECRET not configured');
    return false;
  }

  const expected = 'sha256=' + crypto
    .createHmac('sha256', appSecret)
    .update(body)
    .digest('hex');

  try {
    return crypto.timingSafeEqual(
      Buffer.from(signature),
      Buffer.from(expected)
    );
  } catch (error) {
    console.error('Signature comparison error:', error);
    return false;
  }
}

/**
 * Calls Sugargoo registration endpoint
 */
async function registerWithSugargoo(
  email: string,
  name?: string,
  source: 'website' | 'facebook-lead' = 'facebook-lead'
): Promise<SugargooResponse> {
  // Determine the correct base URL
  let baseUrl = 'https://www.rapid.market';
  
  // In development, use localhost
  if (process.env.NODE_ENV === 'development') {
    baseUrl = 'http://localhost:3000';
  } else if (process.env.NEXT_PUBLIC_SITE_URL) {
    baseUrl = process.env.NEXT_PUBLIC_SITE_URL;
  }

  try {
    const response = await fetch(`${baseUrl}/api/sugargoo/register`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        email,
        name: name || email.split('@')[0],
        // Password is auto-generated by Sugargoo if not provided
        source, // Pass source so register.ts knows not to double-log
      }),
    });

    const data = await response.json();
    return data as SugargooResponse;
  } catch (error) {
    console.error('Sugargoo registration error:', error);
    return {
      code: 500,
      msg: 'Internal registration error',
    };
  }
}

/**
 * Logs registration attempt to analytics
 */
function logRegistration(log: LeadRegistrationLog) {
  console.log('📊 Lead Registration Log:', JSON.stringify(log, null, 2));

  // Optional: Send to external analytics service
  // await sendToAnalytics(log);
}

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const verifyToken = process.env.FACEBOOK_WEBHOOK_VERIFY_TOKEN;

  // Handle GET request (Facebook webhook verification)
  if (req.method === 'GET') {
    const mode = req.query['hub.mode'];
    const token = req.query['hub.verify_token'];
    const challenge = req.query['hub.challenge'];

    if (mode === 'subscribe' && token === verifyToken) {
      console.log('✅ Webhook verified successfully');
      return res.status(200).send(challenge);
    } else {
      console.error('❌ Webhook verification failed');
      return res.status(403).json({ error: 'Verification failed' });
    }
  }

  // Handle POST request (actual lead data)
  if (req.method === 'POST') {
    try {
      // Log incoming webhook for debugging
      console.log('🔔 Webhook received');
      console.log('Headers:', JSON.stringify(req.headers, null, 2));
      console.log('Body:', JSON.stringify(req.body, null, 2));

      // Validate webhook signature (only if present - supports both Facebook and Zapier)
      const signature = req.headers['x-hub-signature-256'] as string;
      
      if (signature) {
        // Facebook sends signature - validate it
        const bodyString = typeof req.body === 'string' ? req.body : JSON.stringify(req.body);

        if (!validateWebhookSignature(bodyString, signature)) {
          console.error('❌ Invalid webhook signature from Facebook');
          return res.status(403).json({ error: 'Invalid signature' });
        }
        console.log('✅ Facebook signature validated');
      } else {
        // No signature (Zapier or test request) - allow it
        console.log('⚠️ No signature header - allowing request (Zapier/test)');
      }

      const body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;

      // Process webhook payload
      console.log('📦 Body received:', JSON.stringify(body, null, 2));
      
      // Handle both Facebook format (with entry) and Zapier format (direct fields)
      let entry = body.entry;
      
      if (!entry) {
        // Check if this is Zapier format - try various field name combinations
        const leadId = body['Lead ID'] || body['lead_id'] || body['leadgen_id'] || '';
        const emailField = body['Email Address'] || body['email'] || body['Email'] || '';
        const nameField = body['Full Name'] || body['full_name'] || body['name'] || body['Name'] || '';
        
        if (emailField) {
          console.log('🔄 Converting Zapier format to Facebook format...');
          console.log('Detected fields:', { leadId, emailField, nameField });
          // Convert Zapier format to Facebook format
          entry = [{
            changes: [{
              field: 'leadgen',
              value: {
                leadgen_id: leadId,
                lead_data: [{
                  email: emailField,
                  full_name: nameField
                }]
              }
            }]
          }];
          console.log('✅ Converted to:', JSON.stringify(entry, null, 2));
        } else {
          console.error('❌ Unknown payload format');
          console.error('Body keys:', Object.keys(body));
          console.error('Body contents:', JSON.stringify(body, null, 2));
          return res.status(400).json({ error: 'Invalid payload: missing entry and no recognized fields detected' });
        }
      }

      if (!Array.isArray(entry)) {
        console.error('❌ Entry is not an array, type:', typeof entry);
        return res.status(400).json({ error: 'Invalid payload: entry must be array' });
      }

      console.log('✅ Payload structure valid, processing', entry.length, 'entries');

      // Process each webhook entry
      for (const item of entry) {
        if (item.changes && Array.isArray(item.changes)) {
          for (const change of item.changes) {
            // Look for leadgen_create events
            if (change.field === 'leadgen') {
              const leadId = change.value?.leadgen_id;
              const leadData = change.value?.lead_data as FacebookLead[] | undefined;

              if (!leadData || !Array.isArray(leadData)) {
                console.warn('⚠️ No lead_data in webhook payload, change:', JSON.stringify(change));
                continue;
              }

              console.log(`📋 Lead data received:`, JSON.stringify(leadData, null, 2));

              // Extract email and name from lead data
              let email: string | undefined;
              let firstName: string | undefined;
              let lastName: string | undefined;

              for (const field of leadData) {
                if (field.email) {
                  email = field.email;
                } else if (field.first_name) {
                  firstName = field.first_name;
                } else if (field.last_name) {
                  lastName = field.last_name;
                }
                // Phone number is captured but not used for Sugargoo registration
              }

              // Email is required
              if (!email) {
                console.warn('❌ Lead missing email field, skipping');
                console.warn('Lead data received:', JSON.stringify(leadData));
                continue;
              }

              // Build full name
              const name = firstName && lastName 
                ? `${firstName} ${lastName}` 
                : firstName || lastName;

              console.log(`📨 Processing lead: ${email} (ID: ${leadId}, Name: ${name || 'N/A'})`);

              // Register with Sugargoo
              console.log(`🔄 Calling Sugargoo registration for ${email}...`);
              const sugargooResponse = await registerWithSugargoo(email, name);
              console.log(`📤 Sugargoo response:`, JSON.stringify(sugargooResponse, null, 2));

              // Log the registration attempt
              const logEntry: LeadRegistrationLog = {
                timestamp: new Date().toISOString(),
                source: 'facebook-lead-ads',
                email,
                name,
                leadId,
                sugargooResponse: {
                  code: sugargooResponse.code || (sugargooResponse.success === true ? 200 : 500),
                  msg: sugargooResponse.msg || sugargooResponse.error || 'No message',
                  userId: sugargooResponse.userId || sugargooResponse.data?.userId,
                  status:
                    sugargooResponse.success === true || sugargooResponse.code === 200
                      ? 'success'
                      : sugargooResponse.code === 40910
                      ? 'duplicate'
                      : 'error',
                },
              };

              logRegistration(logEntry);

              // Handle both response formats:
              // Format 1: {success: true, userId: "...", ...} from register.ts
              // Format 2: {code: 200, msg: "ok", data: {...}} from old API
              
              let analyticsStatus: 'success' | 'duplicate' | 'error' = 'error';
              let errorCode: number | undefined;
              let errorMsg: string | undefined;
              
              if (sugargooResponse.success === true || sugargooResponse.code === 200) {
                const userId = sugargooResponse.userId || sugargooResponse.data?.userId;
                analyticsStatus = 'success';
                console.log(
                  `✅ Account created successfully for ${email} (User ID: ${userId})`
                );
              } else if (sugargooResponse.code === 40910) {
                analyticsStatus = 'duplicate';
                errorCode = 40910;
                errorMsg = 'Email already registered';
                console.log(`⚠️ Email already registered: ${email}`);
                // This is expected behavior - don't error, just log
              } else {
                analyticsStatus = 'error';
                errorCode = sugargooResponse.code || 500;
                errorMsg = sugargooResponse.msg || sugargooResponse.error || 'Unknown error';
                console.error(
                  `❌ Sugargoo registration failed: ${errorMsg}`
                );
              }
              
              // Log to database asynchronously (non-blocking)
              setImmediate(() => {
                logSignupEvent({
                  timestamp: new Date().toISOString(),
                  source: 'facebook-lead',
                  email,
                  status: analyticsStatus,
                  userId: sugargooResponse.userId || sugargooResponse.data?.userId,
                  errorCode,
                  errorMsg,
                });
              });
            }
          }
        }
      }

      // Always return 200 to Facebook immediately (async processing)
      return res.status(200).json({ received: true });
    } catch (error) {
      console.error('Webhook processing error:', error);
      // Still return 200 to Facebook (prevents retries)
      return res.status(200).json({ received: true, error: 'Processing error' });
    }
  }

  // Method not allowed
  return res.status(405).json({ error: 'Method not allowed' });
}
